version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: library-postgres-database
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data