version: '3.8'

services:
  mylibrary:
    image: mylibrary:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    container_name: library-postgres-database-prod-test
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: