spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

api:
  security:
    token:
      secret: "213ddde21edee21"
      expirationTime: 864000000