spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

api:
  security:
    token:
      secret: ${JWT_PRIVATE_TOKEN}
      expirationTime: ${JWT_EXPIRATION_TIME}